
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
      # Applies to all files under models/example/
      example:
          materialized: view

sources:
  - name: cov_sym
    database: bigquery-public-data
    schema: covid19_symptom_search
    tables:
      - name: symptom_search_sub_region_2_weekly

  - name: cov_track
      database: bigquery-public-data
      schema: covid19_tracking
      tables:
        - name: city_level_cases_and_deaths

  - name: cov_mask
      database: bigquery-public-data
      schema: covid19_nyt
      tables:
        - name: mask_use_by_county


{{ source('cov_sym', 'symptom_search_sub_region_2_weekly') }}
{{ source('cov_track', 'city_level_cases_and_deaths') }}
{{ source('cov_mask', 'mask_use_by_county') }}