default:
  outputs:

    dev:
      type: bigquery
      method: oauth
      project: data-engg-313621
      dataset: temp
      threads: 2
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      project: data-engg-313621
      dataset: prod
      keyfile: /home/sehgalvibhor/data-engg-313621-cb0fcd53b5db.json
      threads: 2
      timeout_seconds: 300
      priority: interactive
      retries: 1

  target: dev
