
version: 2

models:
    - name: cases_us
      description: "COVID cases in the US by race"
      columns:
        - name: date
          description: "Date of the data"
        - name: state
          description: "State"
        - name: location
          description: "County"
        - name: city_or_county
          description: "Whether it is a city or county"
        - name: cases_total
          description: "Total COVID cases"
        - name: cases_white
          description: "Total WHITE COVID cases"
        - name: cases_black
          description: "Total BLACK COVID cases"
        - name: cases_latinx
          description: "Total LATINX COVID cases" 
        - name: cases_asian
          description: "Total ASIAN COVID cases"
        - name: cases_aian
          description: "Total AIAN COVID cases"
        - name: cases_hnpi
          description: "Total HNPI COVID cases"
        - name: cases_multiracial
          description: "Total MULTIRACIAL COVID cases"

    - name: symptoms_us
      description: "COVID symptom prominence by counties in the US"

    - name: cases_unpivot
      description: "Unpivoted COVID cases in US - Decomposed race columns as rows"

    - name: symptoms_unpivot
      description: "Unpivoted COVID symptoms in US - Decomposed top 10 symptom columns as rows"

    - name: symptoms_count_null
      description: "Count of null values for each symptom mentioned in symptoms_us"

    - name: symptoms_unpivot_cleaned
      description: "symptoms_unpivot aggregated at a month-year level"

    - name: county_code_mapping
      description: "County code and name mapping for US"
      columns:
        - name: county_code
          description: "FIPS code of the county"
          tests:
            - unique
            - not_null
        - name: state
          description: "State the county belongs to"
        - name: county
          description: "County Name"

    - name: race_symptoms
      description: "Race and COVID symptoms joined and aggregated at a county and month level"

    - name: top_race_symptoms
      description: "Ranked symptoms by race for at a county and month level"

    - name: top_covid_symptoms_by_race
      description: "Transformed top_race_symptoms to populate the top symptoms against each race in the order of their prominence"

    - name: covid_symptoms_by_rank_and_race
      description: "Transformed top_race_symptoms to create columns for each symptom with rank"

    - name: race_symptom_mask_uasge
        description: "Merged the top_covid_symptoms_by_race data with county-wise mask usage data"
        columns:
          - name: state
            description: State
          - name: county
            description: County
          - name: month
            description: Month
          - name: race
            description: Race
          - name: first
            description: First common symptom
          - name: second
            description: Second common symptom
          - name: third
            description: Third common symptom
          - name: fourth
            description: Fourth common symptom
          - name: fifth
            description: Fifth common symptom
          - name: sixth
            description: Sixth common symptom
          - name: seventh
            description: Seventh common symptom
          - name: eighth
            description: Eighth common symptom
          - name: ninth
            description: Ninth common symptom
          - name: tenth
            description: Tenth common symptom
          - name: never
            description: Percentage of people in the county who never wear masks
          - name: rarely
            description: Percentage of people in the county who rarely wear masks
          - name: sometimes
            description: Percentage of people in the county who sometimes wear masks
          - name: frequently
            description: Percentage of people in the county who frequently wear masks
          - name: always
            description: Percentage of people in the county who always wear masks



